### PR TITLE
kernel-hw-devices/module-alias-usage.dia: fix layout

### PR DESCRIPTION
**Pull request by arnout**
When I open this figure, the 'the asix module is loaded' star appears on the very top right, far away from the figure itself. As a result, that star is the only thing shown on the slide.

Move the star down to the position I _think_ is the proper one.

While using the bootlin materials for an internal training, there are a few improvements I made (at least, I consider them improvments myself). Since you probably don't agree with all of them, I'm making separate PRs for each. Feel free to close the PR if you disagree with the idea.

### CODE REVIEW

**Review by miquelraynal — COMMENTED** [review]
That's very strange, I don't have this issue here. Plus, the "new" dia file has two wrong arrows:
- the one from "make modules_install" towards modules.alias is missing
- the one from "The USB controller driver reads..." is now pointing at modules.alias
Also, the RJ45/USB hardware picture is now missing.
I am using Dia 0.97.3.
Our build server also does not show the problem (the auto-generated content looks fine on this regard).

**Comment by arnout** [comment]
I have Dia 0.97.3 on Fedora.

The two incorrect arrows are exactly like that when I open the file. So it seems that after I open and re-save in my version, it does look "correct" on your side... For reference, here's a screenshot of what the original looks like when I open it in Dia.

image

Since it works correctly on the build server, I guess it's best to not touch things. Bad luck for anyone with a "wrong" Dia if they try to regenerate the slides :-)

Alternatively, you could try to make a slight change on your side and re-save, perhaps that fixes things...

For sure, there's no point merging as is, so I'll close this PR.

**Comment by miquelraynal** [comment]
Good idea: https://github.com/bootlin/training-materials/commit/7dc297e519536ec896d8ad13dc8e6fddf3580efe
Does it fixes the rendering on your side?

**Comment by arnout** [comment]
> Good idea: [7dc297e](https://github.com/bootlin/training-materials/commit/7dc297e519536ec896d8ad13dc8e6fddf3580efe) Does it fixes the rendering on your side?

Nope, same issue. Not such a good idea after all :-)

I noticed now though that Dia at startup complains with "Unknown types while reading diagram file
Standard - Path". Not sure what to make of that. It seems to hint that there may be some template library or something that I'm missing?

**Pull request closed without merging**
