### PR TITLE
Yocto agenda refactoring

### PR DESCRIPTION
**Pull request by Taumille**
These 3 commits refactor the yocto agendas, starting from here, every structural commits which affects the yocto trainings will have to be done on `yocto.inc`.

The different yocto-agenda-*.tex files only contains information on : 
- the language 
- the type of training (onsite/online)
- and the different supported boards

Those commits also affects the way LaTeX prints the available boards for future refactoring of other training.

### CODE REVIEW

**Comment by tpetazzoni** [comment]
Thanks for your work on this!

I think the split of the commits isn't ideal. Indeed, the first commit introduces some of the infrastructure *and* refactors one agenda, and the second commit introduces a bit more infrastructure *and* refactors the remaining agendas.

I would prefer to have one commit that introduces the infrastructure (new macros), one commit that introduces the definition of the agenda items for the Yocto course, and one commit that refactors all Yocto agendas to use this new infrastructure.

Ditto for the board refactoring IMO.

Also, one element in the agenda that isn't refactored in your series is the QA session at the end. I know when don't have it in a consistent way today, but we should take advantage of this refactoring to bring more consistency on this topic.

**Comment by Tropicao** [comment]
recheck

**Comment by Tropicao** [comment]
recheck

**Comment by tpetazzoni** [comment]
Thanks, I have merged this pull request, after doing some changes. Most notably, the macro \showagendaday{} was meant to be a generic macro between on-line and on-site agendas, but you only used it for on-line agendas, which didn't make much sense. So in the end, I dropped \showagendaday{} entirely, which removed the need for the pgf package.

I also added some documentation, and slightly improved a few other things. I made my fixes/changes as separate commits so that you can review them.

Thanks a LOT for this great work. Now we can proceed with the next step: moving to a new template for the agendas!

**Pull request closed without merging**
