### PR TITLE
labs/yocto-add-application: move splitting the recipe at the end

### PR DESCRIPTION
**Pull request by cperrysfl**
IMO, it is unnecessary to split the recipe into a .inc and a .bb from the start as it delays the main part of the lab.

Also ask the student to start building as soon as possible, even if the recipe is not complete.

Regards,
Charles

### CODE REVIEW

**Comment by lucaceresoli** [comment]
When doing the lab as a demo during online trainings I always start the build when the recipe is still incomplete and I agree this is useful to show how a recipe can be written step by step, and also some of the errors one may get when the recipe is not (yet) correct and how to handle this.

Writing the recipe split in bb+inc from the beginning never appeared as an issue to me, however splitting it later on can make sense to further split the process in small steps.

**Comment by cperrysfl** [comment]
Hello Luca!

Thank you for the feedback.

No problem if you don't want this, I'll close the PR.

**Comment by lucaceresoli** [comment]
Hello Charles,

I think my wording was not very clear, I think the proposed change of writing the recipe as a single file and then split it is good, only I never found the current code problematic.

Additionally the idea of running the build when the recipe is not yet completely and correctly written is totally good, and it is exactly what I do during  online trainings.

I still haven't reviewed all the details of your patch but at a quick glance it looks good and I plan to take it.

However before I apply these changes, I need to ask you whether you agree to give us "public domain" usage rights for them, as well as the other changes from you. If you do, your name will be kept in the commit history so authorship attribution will be honoured, but we would like Bootlin to keep the ability to switch to a different license (or license version number) for these materials, or to give a license exception to a customer funding some improvements or customizations.

Let me know whether you agree with this.

Thanks again for your contributions.

**Comment by alexandrebelloni** [comment]
I would honestly drop splitting the recipe as the current trend is to stop doing that so devtool can upgrade the recipe automatically.

**Comment by lucaceresoli** [comment]
Commit merged, thanks @cperrysfl 
Also removed the .inc/.bb split with a follow-up commit.

**Pull request closed without merging**
