### PR TITLE
Sysdev kernel building improvements

### PR DESCRIPTION
**Pull request by arnout**
While using the bootlin materials for an internal training, there are a few improvements I made (at least, I consider them improvments myself). Since you probably don't agree with all of them, I'm making separate PRs for each. Feel free to close the PR if you disagree with the idea.

### CODE REVIEW

**Review by miquelraynal — APPROVED** [review]

**Comment by Tropicao** [comment]
recheck

**Comment by Tropicao** [comment]
Hello @arnout, sorry for the long delay on your pull requests processing. In the mean time, we have slightly updated our external contribution workflow (mostly to automate it instead of manually gathering contributors agreement), then we need you to perform (only once, not for each PR) the action requested by the bot above, even if have manually agreed in the past to those terms. Thanks !

**Comment by arnout** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by Tropicao** [comment]
recheck

**Pull request merged**
